### ISSUE TITLE
cant install it 

### ISSUE THREAD

**Issue by Ei187** [drndos/mikettle-ha#8]
sorry about my bad english 
my frind i cant install pip3 install bluepy or do sudo commend on ha os terminal system,
can i install it difrrent way or do something else ?
i try evrething and still get  this error
"Platform error switch.mikettle - Integration 'mikettle' not found."
pls help 
and thx about all the good work

**Comment by Worrah** [comment]
same for me :(

```
2023-05-28 21:12:02.076 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1881486072] The system cannot restart because the configuration is not valid: Platform error sensor.mikettle - Integration 'mikettle' n>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 756, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 174, in async_handle_core_service
    raise HomeAssistantError(

```

**Comment by Worrah** [comment]
solved with adding a version=1.0.0 in manifest.json 

UPD: unusable anyway, not updating and even with that you cant connect to a kettle in MiHome after that. Assuming, because of the polling spam
